#!/bin/bash
# Analyse ACCORD BAG predictions generated by dkgp_training.py
# Reads: models/bag_fold{0-4}/accord_predictions_BAG_0_{fold}.csv
# Writes: analysis/accord_bag/

set -e

python analyze_accord_predictions.py \
    --models_dir  models \
    --accord_data data/accord_data_bag_processed.csv \
    --output_dir  analysis/accord_bag \
    --n_folds     5 \
    --biomarker   BAG \
    --biomarker_index 0 \
    --n_traj      20

echo ""
echo "Figures saved to: analysis/accord_bag/"
